Stories Feature
keepid/team-keep pull request #34
Opened 2021-09-21 03:16 UTC by ykl1

2021-10-21 02:41 UTC, crchong1 commented on src/static/styles/App.scss
> +	font-family: "Poppins", sans-serif;
can we stick to Inter?

2021-10-21 02:41 UTC, crchong1 commented on src/static/styles/App.scss
> +	color: #0d0d0d;
I would move all colors to a variable, and declare them at the top

2021-10-21 02:41 UTC, crchong1 commented on src/static/styles/App.scss
> +	color: #fafafa;
move color to variable

2021-10-21 02:43 UTC, crchong1 commented on src/components/Stories.tsx
> +    axios.get(url).then((response) => {
do you have any additional thoughts on using axios? I know right now we usually use fetch, but is there a specific reason why you chose axios?

2021-10-21 02:43 UTC, crchong1 requested changes
see comments

2021-10-25 21:42 UTC, ykl1 commented on src/components/Stories.tsx
> +    axios.get(url).then((response) => {
I could use fetch! Axios has wider browser compatibility than fetch, and it automatically transforms responses into json data, which makes the code a bit cleaner than fetch.

2021-10-26 00:44 UTC, crchong1 approved these changes

2021-10-26 01:15 UTC, merged